name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        node_version: [
          20,
          22,
          24
        ]
        peer_version: [
          { nest: 11, swagger: 11 },
          { nest: 12, swagger: 12 }
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v6
        with:
          version: 12
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint && pnpm run build

      - run: |
          pnpm -C example/typescript-starter add \
            @nestjs/common@^${{ matrix.peer_version.nest }} \
            @nestjs/core@^${{ matrix.peer_version.nest }} \
            @nestjs/platform-express@^${{ matrix.peer_version.nest }} \
            @nestjs/testing@^${{ matrix.peer_version.nest }} \
            @nestjs/cli@^${{ matrix.peer_version.nest }} \
            @nestjs/schematics@^${{ matrix.peer_version.nest }} \
            @nestjs/swagger@^${{ matrix.peer_version.swagger }}
          pnpm run test-swagger${{ matrix.peer_version.swagger }}



