name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        node_version: [
          20,
          22,
          23
        ]
        peer_version: [
          { common: 10, swagger: 7 },
          { common: 10, swagger: 8 }
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint && pnpm run build

      # if swagger: 8 then run test:swagger8 else swagger7, etc.
      - run: |
          pnpm -C example/typescript-starter add @nestjs/common@^${{ matrix.peer_version.common }} @nestjs/swagger@^${{ matrix.peer_version.swagger }}
          pnpm run test-swagger${{ matrix.peer_version.swagger }}



